# Use the official MongoDB 6.0 image
FROM mongo:6.0

# Set environment variables (can also be overridden in the docker-compose file)
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=rootpassword

# Expose the default MongoDB port
EXPOSE 27017
