# Use the official MySQL 8.0 image
FROM mysql:8.0

# Set environment variables (can also be overridden in the docker-compose file)
ENV MYSQL_ROOT_PASSWORD=Password@123
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=Password@123

# Expose the default MySQL port
EXPOSE 3306
